import os
import pandas as pd

# for _ in pd.date_range('2024-01-01', '2024-04-01', freq='D'):
#     print(_.strftime('%Y-%m-%d'))
#     os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path shanxi_elec.csv --model_id shanxi_{} --model iTransformer --data shanxi --features MS --seq_len 672 --label_len 96 --pred_len 96 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 11 --dec_in 11 --c_out 1 --d_model 128 --d_ff 128 --des Exp --itr 1 --top_k 5 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))
    
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path shanxi_elec.csv --model_id shanxi_{} --model VMD_LSTM --data shanxi --features S --seq_len 672 --label_len 96 --pred_len 96 --target dayahead_price1 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des Exp --itr 1 --top_k 5 --learning_rate 0.00001 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))# --d_model 128 --d_ff 128
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path shanxi_elec.csv --model_id shanxi_{} --model VMD_LSTM --data shanxi_per_point --features S --target dayahead_price1 --seq_len 672 --label_len 1 --pred_len 1 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des Exp --itr 1 --top_k 5 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))# --d_model 128 --d_ff 128

# os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path shanxi_elec.csv --model TimesNet --data shanxi_elec --features MS --seq_len 96*7 --label_len 96 --pred_len 96 --e_layers 2 --d_layers 1 --factor 3 --enc_in 11 --dec_in 11 --c_out 1 --d_model 16 --d_ff 32 --des 'Exp' --itr 1000 --top_k 5')

for _ in pd.date_range('2023-07-05', '2023-12-31', freq='D'):
    print(_.strftime('%Y-%m-%d'))
    os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model TSMixer --data iso_new_england --features MS --seq_len 168 --label_len 24 --pred_len 24 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 9 --dec_in 9 --c_out 1 --d_model 128 --d_ff 128 --des Exp --itr 1 --top_k 5 --down_sampling_layers 3 --down_sampling_method avg --down_sampling_window 2 --learning_rate 0.0003 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d'))) 
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model VMD_LSTM --data iso_new_england_per_point --features S --target Price --seq_len 168 --label_len 1 --pred_len 1 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des Exp --itr 1 --top_k 5 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))# --d_model 128 --d_ff 128
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model PatchTST --data iso_new_england --features MS --seq_len 168 --label_len 24 --pred_len 24 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 9 --dec_in 9 --c_out 1 --d_model 128 --d_ff 128 --des Exp --itr 1 --top_k 5  --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model TimesNet --data iso_new_england --features S --target Price --seq_len 168 --label_len 24 --pred_len 24 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --d_model 128 --d_ff 128 --des Exp --itr 1 --top_k 5  --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))

#     os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model VMD_LSTM --data iso_new_england_per_point --features S --target Price --seq_len 168 --label_len 1 --pred_len 1 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --des Exp --itr 1 --top_k 5 --learning_rate 0.000005 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))
    # os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_new_england.csv --model_id iso_{} --model DNN --data iso_new_england --features MS --seq_len 168 --label_len 24 --pred_len 24 --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 9 --dec_in 9 --c_out 1 --d_model 128 --d_ff 128 --des Exp --itr 1 --top_k 5  --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))

# for _ in pd.date_range('2023-01-01', '2023-09-30', freq='D'):
#     print(_.strftime('%Y-%m-%d'))
#     os.system('python -u run.py --task_name long_term_forecast --is_training 1 --root_path ./data/ --data_path iso_capacity_only.csv  --seasonal_patterns Yearly --model_id iso_capacity_{} --model TimesNet --data iso_capacity --features S --seq_len 14 --label_len 2 --pred_len 2 --target Total_Available_Capacity --inverse  --e_layers 2 --d_layers 1 --factor 3 --enc_in 1 --dec_in 1 --c_out 1 --d_model 16 --d_ff 32 --des \'Exp\' --itr 1 --top_k 5 --tgt_dt {}'.format(_.strftime('%Y-%m-%d'), _.strftime('%Y-%m-%d')))
